### ISSUE TITLE
Does the --parsesamplesheet option still exist?

### ISSUE THREAD

**Issue by lfaller** [lskatz/SneakerNet#39]
Hello! I am trying to run your tool through the docker container.

Does the `--parsesamplesheet` option, as referenced in the container help docs, still exist? Or is `--createsamplesheet` a better route to set up an initial MiSeq run?

Thanks,
~Lina

**Comment by lskatz** [comment]
You are correct that it is `--createsamplesheet`!  This is an error in documentation and has been fixed in ff64627

Additionally, I created a new script `scripts/sn_createSampleSheet.pl` to take care of the single task of making the sample sheet in f52fc2260cfe7805594ddb3a313676ed4e19407a but it was undocumented.  I finally documented it in ff64627.
